defaults:
  - _self_

model: cifar10_vit
temperature: 1.0
use_acc: True
epochs: 10

optimizer:
  name: adam
  lr: 1e-4
  
  weight_decay: 0. #5e-4
  scheduler: #StepLR
  step_size: 2
  gamma: 0.8


  