defaults:
  - _self_

model: cifar100_densenet121
temperature: 1.0
use_acc: True
epochs: 10

optimizer:
  name: adam
  lr: 3e-4
  
  weight_decay: 0. #5e-4
  scheduler: #StepLR
  step_size: 2
  gamma: 0.8


  