defaults:
  - _self_

model: cifar100_resnet50
temperature: 1.0
use_acc: True
epochs: 10

optimizer:
  name: adam #adam
  lr: 3e-4
  
  weight_decay: 5e-4
  scheduler: StepLR
  step_size: 7
  gamma: 0.8


  