defaults:
  - _self_

model: tissue_resnet
temperature: 1.0
use_acc: True
epochs: 10

optimizer:
  name: adam
  lr_fc: 5e-4
  lr_layer4: 1e-4
  weight_decay: 5e-4
  scheduler: StepLR
  step_size: 5
  gamma: 0.5


  