num_features : 
num_classes : 9 # 10 classes but fixed no need to specify
random_state : 42
batch_size : 512 # 1024 for calibration and 32 for pre-training
variant: #'awgn', 'motion_blur', 'reduced_contrast'
size: 224
